FROM node:20-alpine

WORKDIR /app
ENV PNPM_HOME=/usr/local/pnpm
ENV PATH="$PNPM_HOME/bin:$PATH"

RUN corepack enable && corepack prepare pnpm@10.18.2 --activate

COPY package.json pnpm-lock.yaml ./
RUN CI=true pnpm install --frozen-lockfile

COPY . .

ENV FRONTEND_PORT=5173
EXPOSE ${FRONTEND_PORT}
CMD sh -c "pnpm dev --host 0.0.0.0 --port ${FRONTEND_PORT}"
